#!/bin/sh
set -e

# Path to the .env.local file
ENV_FILE=".env.local"

echo "Running entrypoint.sh..."

# Create or clear the .env.local file
echo "# Generated by entrypoint.sh from environment variables" > "$ENV_FILE"

# List of environment variables to export to .env.local
# Agent API keys
VARS="OPENROUTER_API_KEY GEMINI_API_KEY CURSOR_API_KEY ANTHROPIC_API_KEY"
# Nango integration
VARS="$VARS NANGO_SECRET_KEY NANGO_DEFAULT_USER_ID"
# Vercel Sandbox credentials
VARS="$VARS VERCEL_TOKEN VERCEL_TEAM_ID VERCEL_PROJECT_ID"
# App configuration
VARS="$VARS MCP_REGISTRY_URL NEXTAUTH_URL NEXTAUTH_SECRET NEXT_PUBLIC_GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET"
# Database
VARS="$VARS DATABASE_URL POSTGRES_URL"
# Security
VARS="$VARS JWE_SECRET ENCRYPTION_KEY"
# Runtime
VARS="$VARS SKILLS_DIR PORT NODE_ENV DOCKER_INTERNAL_HOST"

for var in $VARS; do
    # Use eval to safely get the value of the variable name stored in $var
    val=$(eval echo "\$$var")
    if [ -n "$val" ]; then
        echo "Found environment variable: $var"
        echo "$var=\"$val\"" >> "$ENV_FILE"
    else
        echo "Environment variable not found or empty: $var"
    fi
done

echo ".env.local generation complete."

# Run database migrations
echo "Running database migrations..."
export HOME=/app
export npm_config_cache=/app/.npm
node_modules/.bin/drizzle-kit migrate

echo "Migrations completed."

# Execute the main container command
exec "$@"
